### ISSUE TITLE
Scheduling Tasks - complete/src/test/* seems not needed

### ISSUE THREAD

**Issue by josephzhang999** [spring-guides/getting-started-guides#143]
In the downloaded source repository for this guide, there are two test files: SchedulingTasksApplicationTest.java, ScheduledTasksTest.java.

The guide doesn't introduce / explain the details in these two files. And they are not needed (without them, the application can still run and print out the current time to the log every 5 seconds).

Therefore, it seems they can be removed from the source repository.
The part of "Adding the awaitility Dependency" in the guide can also be removed (I tried, it still works).

Thanks for the consideration. I'm new to Spring so if there is any wrong inputs, please excuse me. Your feedback to this issue is appreciated.

**Comment by robertmcnees** [comment]
Hi @josephzhang999. Thank you for your issue. You are correct that the `gs-scheduling-tasks` guide could use some work.

I will close this issue because I believe it is covered under the issues in the [gs-scheduling-tasks GitHub repo](https://github.com/spring-guides/gs-scheduling-tasks).

- [Needs a rewrite](https://github.com/spring-guides/gs-scheduling-tasks/issues/28)
- [Inconsistent versions used for awaitility](https://github.com/spring-guides/gs-scheduling-tasks/issues/31)

You will be able to track progress by monitoring those issues and the attached PR(s). Thanks again,
